name: Create EC2 Instance
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create EC2 Instance
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Create CloudFormation Stack
      #  uses: aws-actions/amazon-cloudformation-action@v1
        with:
          stack-name: my-ec2-instance
          template-body: |
            ---
            AWSTemplateFormatVersion: '2010-09-09'
            Parameters:
              InstanceType:
                Type: String
                Description: EC2 instance type
              KeyName:
                Type: String
                Description: Name of the KeyPair to use for the instance
              ImageId:
                Type: AWS::SSM::Parameter::Value<String>
                Description: ID of the Amazon Machine Image (AMI) to use
              SecurityGroup:
                Type: AWS::EC2::SecurityGroup::Id
                Description: ID of the security group to assign to the instance
              SubnetId:
                Type: AWS::EC2::Subnet::Id
                Description: ID of the subnet to launch the instance in
            Resources:
              EC2Instance:
                Type: 'AWS::EC2::Instance'
                Properties:
                  InstanceType: !Ref InstanceType
                  KeyName: !Ref KeyName
                  ImageId: !Ref ImageId
                  SecurityGroupIds:
                    - !Ref SecurityGroup
                  SubnetId: !Ref SubnetId
        
          parameters: |
            {
              "InstanceType": "t2.micro",
              "KeyName": "linuxkey",
              "ImageId": "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2",
              "SecurityGroup": "sg-0eb6957b27a912897",
              "SubnetId": "subnet-00aa235b567759287"
            }
